### PR TITLE
feat: support object-form JSON-LD context

### LINKED ISSUE #21: ConvertContext doesn't support object-form context
Unfortunately, it is possible to construct a cursed (but valid!) ActivityPub object of this shape:
```json
{
  "@context": {
    "@import": "https://www.w3.org/ns/activitystreams"
  },
  "type": "Note",
  "...": "etc"
}
```
This will crash [ConvertContext](https://github.com/Letterbook/Letterbook.ActivityPub/blob/main/Letterbook.ActivityPub/ConvertContext.cs) as it only handles objects when they are elements of an array. I don't *think* anyone is doing this in practice, but I can imagine a scenario where some JSON-LD tooling tries to "optimize" the context by merging everything down. See this for more info about `@import`: https://www.w3.org/TR/json-ld11/#imported-contexts.

### PR DESCRIPTION
**Pull request by warriordog**
Expands `ConvertContext` to handle object-only forms of the JSON-LD `@context` property. This allows more advanced JSON-LD constructions to be parsed and serialized correctly. This fixes #21.

### CODE REVIEW

**Comment by warriordog** [comment]
This additionally introduces FluentAssertions as a library to assist with unit tests. If you don't want that, I can remove it and re-implement the tests manually.

**Comment by jenniferplusplus** [comment]
TBH, I'm not sure what makes this less manual than using xUnit built in assertions. But either way, I'm not a fan of fluent assertions. I'd rather test code look more like application code.

**Comment by warriordog** [comment]
@jenniferplusplus totally fair - I'll swap that for normal methods. But if you're curious, assertion libraries really shine when you want to make complex assertions against collections or untyped objects. I also like the extensibility of FluentAssertions, like this: https://github.com/warriordog/ActivityPubSharp/blob/main/Tests/ActivityPub.Types.Tests/Util/Assertions/JsonElementAssertions.cs

**Comment by warriordog** [comment]
@jenniferplusplus pushed another commit to remove FluentAssertions. I've never worked with xUnit assertions directly, so let me know if I did anything wrong with this.

**Review by jenniferplusplus — APPROVED** [review]
@warriordog Those tests look fine, thank you for doing this. I spent some time earlier getting CI to work properly from a fork. I think I've got it now. Can you pull from main before we merge?

**Comment by warriordog** [comment]
@jenniferplusplus You're very welcome! There's a major lack of functional ActivityPub stuff using C#, and I'm glad to help fix that. My own project is moving way slower since I'm trying for complete spec compliance.

Just pulled changes, so the PR should be up-to-date.

**Pull request merged**
